### ISSUE TITLE
[Errno 2] on tmp3D.png file

### ISSUE THREAD

**Issue by wprjrdev** [clement-roblot/Gridfinity-Label-Generator#8]
I'm getting an Errno 2 when attempting to add an image, which appears to involve an issue opening/creating the tmp3D.png file. I've checked the directory permissions and they're set to allow read/write. Is the app supposed to generate this tmp3D.png file or is it something that needs to be created using a graphics app and dropped into the folder?

Traceback follows:

Traceback (most recent call last):
  File "/Users/filepath/to//Gridfinity-Label-Generator-main/mainWindow.py", line 176, in exportFile
    generateLabelSheets(self.getData(), fileName)
  File "/Users/filepath/to//Gridfinity-Label-Generator-main/mainWindow.py", line 151, in getData
    self.refresh()
  File "/Users/filepath/to//Gridfinity-Label-Generator-main/mainWindow.py", line 195, in refresh
    self.stickerForm.loadData(self.stickerList.currentItem())
  File "/Users/filepath/to//Gridfinity-Label-Generator-main/stickerForm.py", line 195, in loadData
    self.refresh3DViewFull()
  File "/Users/filepath/to//Gridfinity-Label-Generator-main/stickerForm.py", line 158, in refresh3DViewFull
    img = makeLinesThicker("tmp3D.png")
  File "/Users/filepath/to//Gridfinity-Label-Generator-main/generator.py", line 51, in makeLinesThicker
    img = Image.open(imagePath)
  File "/Users/filepath/to/micromamba/envs/pyoccenv/lib/python3.8/site-packages/PIL/Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/filepath/to//Gridfinity-Label-Generator-main/tmp3D.png'

**Comment by clement-roblot** [comment]
Interesting.... This "tmp3D.png" is the last 3d render generated by the open CASCADE lib. I suspect for some reason it fails with the model you inputed and thus the file isn´t created and then it crashes cause it's your first render so it doesn´t even fallback on previous renders.

Could you try to put this file in your repo (at the root of the repo):
![tmp3D](https://github.com/user-attachments/assets/b47992fd-1644-4edb-a262-752ab48296ea)

I suspect this will prevent the out right crash of the system. Then once it doesn't crash anymore you should be able to play with the angles of the 3d render. With some models and some specifics angles, the rendering fails (no idea why, it feels a bit like some sort of a gimbal lock kinda situation). So play around with both angles and hopefully your model will be rendered.

**Comment by wprjrdev** [comment]
Thanks. Working now!

**Comment by clement-roblot** [comment]
This commit should prevent this issue from happening again: 565e20d7487d91d5dc0f19fc60b633e38253c9c9
